### ISSUE TITLE
Notifcation when pilot qualifies for Commendation of Bravery

### ISSUE THREAD

**Issue by TheBlackxRanger** [emperorshammer/issues-incoming-queue#160] opened 2023-04-05 00:26 UTC
In regards to the [CoB page](https://tc.emperorshammer.org/cob.php) which lets you know *if* a pilot qualifies for a COB, a quality of Life improvement can be notifying a CMDR (via email or system message) when a pilot meets the 30 mission threshold which would expedite delivery of CoBs.

**Comment by turtlexiv** [comment] 2023-04-08 15:17
Duplicate of emperorshammer/tiecorps#63 ; we're going to end up fully automating this.

**Closed as completed** 2023-04-08 15:18 UTC
Labels: duplicate
