### ISSUE TITLE
Redirect from management.php to login.php

### ISSUE THREAD

**Issue by robertehogan** [emperorshammer/issues-incoming-queue#53] opened 2022-02-17 21:10 UTC
Feature request or possible bug?
For pages that are only accessible to registered users, redirect guests automatically (or include a link) to the login page.  Currently, visiting management.php without authentication results in an error, while on the previous version of the site, you were redirected to the login page.

**Comment by turtlexiv** [comment] 2022-02-18 22:49
Thanks for the suggestion.  This is already on the list.

Duplicate of emperorshammer/tiecorps#250

**Closed as completed** 2022-02-18 22:49 UTC
