### ISSUE TITLE
REQUEST: Drag/Drop Image Files

### ISSUE THREAD

**Issue by VictorianVader** [emperorshammer/issues-incoming-queue#77] opened 2022-03-21 20:21 UTC
I used to be able to drag and drop image files into the upload sections instead of using the "choose a file" function (for example, uploading victory screenshots for LOC/LOS submissions).  Any way to add this functionality on the new site?

Thanks,
Westric Davalorn

**Comment by turtlexiv** [comment] 2022-04-07 19:37
This is already a known issue and in the queue to be worked.

Closing as a duplicate of emperorshammer/tiecorps#258 .

**Closed as completed by turtlexiv** 2022-04-07 19:37 UTC
Labels: duplicate
