### ISSUE TITLE
Minor new feature - ID line line breaks

### ISSUE THREAD

**Issue by robertehogan** [emperorshammer/issues-incoming-queue#60] opened 2022-02-23 21:55 UTC
**== New feature request ==**
In the previous website layout, pilot ID lines were included with line breaks in them, so that longer ID lines were spread over three or more lines.  This made it very convenient for pasting into email clients, since the ID lines were already formatted in a manageable way.  If possible, it would be great to see this come back in some way.

**== Examples ==**
**New:**
> SSx7/BSx9/PC/ISMx2/IAR/MoT-gh/MoC-doc-poc-goc-2soc-10boc/IS-6GW-6SW-11BW-PR-3GR-10SR-13BR-4CR/LoC-PS/LoS-RS/CoL/CoB/OV

> {TCCORE-MCBS-MP/2-SM/5-TM/3-WIKI}

**Old:**
> SSx7/BSx9/PC/ISMx2/IAR/MoT-1gh/MoC-1poc-1goc-1soc-7boc/IS-6GW-6SW-11BW-1PR-3GR-10SR-

> 13BR-4CR/LoC-PS-RS-TS-IS-CSx3-Rx1/LoS-TS-IS-CSx9-Rx1/CoL/CoB/OV [Dragoon] [Elite 3rd]

> [Gunner's Mate 4th] {TCCORE-MCBS-MP/2-SM/5-TM/3-WIKI}

**Comment by MrPliffles** [comment] 2022-02-24 01:23
The problem is that everyone's ID line is different, there's not always going to be a sweet spot where inserting a line break makes sense.

The new site also omits the three combat ratings and I'm not sure that's intended.

**Comment by turtlexiv** [comment] 2022-09-01 01:56
This will be addressed in emperorshammer/tiecorps#545 .

**Closed as not planned by turtlexiv** 2022-09-01 01:56 UTC
Labels: duplicate
