### ISSUE TITLE
Suggestion - Competition Filter

### ISSUE THREAD

**Issue by kazraran** [emperorshammer/issues-incoming-queue#203] opened 2023-11-12 22:36 UTC
It would be nice if the competition listing page (https://tc.emperorshammer.org/competitions.php?id=current) had a filter to only show those competitions I'm eligible to participate in (e.g., remove the ones that are only for squads I'm not a part of).

**Comment by turtlexiv** [comment] 2023-11-23 14:50
This is a planned future enhancement as part of some overall improvements to the competition process.  We have an issue open for it already internally.

Closing this one as a duplicate.

Duplicate of emperorshammer/tiecorps#44 .

**Closed as completed by turtlexiv** 2023-11-23 14:50 UTC
Labels: duplicate
