### ISSUE TITLE
Automate FCHG, Combat Rating, and Co-Op PvE Rating medals being awarded

### ISSUE THREAD

**Issue by Solohan50** [emperorshammer/issues-incoming-queue#93] opened 2022-04-23 18:20 UTC
Per the conversation in JV chat, please see about automating these medals when they're awarded.

**Comment by turtlexiv** [comment] 2022-08-31 22:09
Per the TCCOM, we are not automating these (and because there is no way for the system to know which medals have previously been issued it wouldn't work brilliantly anyway).  However, we will be adding a mechanism that alerts when pilots pass thresholds and become eligible.

Closing as a duplicate of emperorshammer/tiecorps#58 .

**Closed as completed by turtlexiv** 2022-08-31 22:09 UTC
