### ISSUE TITLE
Refill option

### ISSUE THREAD

**Issue by MarentaJean** [emperorshammer/issues-incoming-queue#56] opened 2022-02-18 14:29 UTC
When you use the refill option, if you have multiple players, it only loads the top line. You have to click "add new line" to see the remaining lines. Could be nature of the game I submitted, I'm sure if it were 5v5, it may have loaded more.

Obviously, VERY low priority. Like, bottom of the list.

**Comment by turtlexiv** [comment] 2022-02-18 22:42
Known issue.

Duplicate of emperorshammer/tiecorps#273

**Closed as completed** 2022-02-18 22:42 UTC
